export const customerRoleIds = Object.freeze(["designer", "contractor", "supplier", "developer-procurement", "private-owner", "other"]);
export const productFormVariant = "product-role-v2";
export const fullFormVariant = "full-role-v2";

export const inquiryIntakeCopy = {
  en: { destination: "Delivery city / region and country", destinationHint: "e.g. Austin, TX, USA", materialStudy: "Illustrative material study; not a workshop or completed-project photograph.", drawingStudy: "Illustrative concept study; not a client-approved project drawing.", role: "Your role", email: "Email", company: "Company / studio (optional)", budget: "Budget range (optional)", optional: "Add optional company, phone, budget or timing", budgetHint: "Amount and currency, or undecided", roles: ["Designer / architect / art consultant", "Contractor", "Supplier", "Developer / procurement team", "Private owner", "Other"], message: "Project use and approximate size", messageHint: "Where will it be used, and what size do you have in mind? Include units; “undecided” is fine. We can also review your own drawing." },
  zh: { destination: "项目交付城市 / 地区与国家", destinationHint: "例如：美国得克萨斯州奥斯汀", materialStudy: "材料示意研究，并非真实车间或已完工项目照片。", drawingStudy: "概念示意研究，并非客户已批准的项目图纸。", role: "您的角色", email: "邮箱", company: "公司 / 工作室（选填）", budget: "预算范围（选填）", optional: "补充公司、电话、预算或时间（选填）", budgetHint: "金额和币种，或填写未定", roles: ["设计师 / 建筑师 / 艺术顾问", "承包商", "供应商", "开发商 / 采购团队", "私人业主", "其他"], message: "项目用途与大致尺寸", messageHint: "用于什么场地，大致需要多大？请注明单位，尚未确定可写“未定”。也可按您的图稿评估定制。" },
  ar: { destination: "مدينة / منطقة وبلد التسليم", destinationHint: "مثال: أوستن، تكساس، الولايات المتحدة", materialStudy: "دراسة توضيحية للمواد؛ ليست صورة ورشة أو مشروع مكتمل.", drawingStudy: "دراسة مفاهيمية توضيحية؛ ليست رسماً لمشروع معتمداً من العميل.", role: "دورك", email: "البريد الإلكتروني", company: "الشركة / الاستوديو (اختياري)", budget: "نطاق الميزانية (اختياري)", optional: "إضافة الشركة أو الهاتف أو الميزانية أو الموعد (اختياري)", budgetHint: "المبلغ والعملة، أو غير محدد", roles: ["مصمم / معماري / مستشار فني", "مقاول", "مورّد", "مطوّر / فريق مشتريات", "مالك خاص", "أخرى"], message: "استخدام المشروع والحجم التقريبي", messageHint: "أين سيُستخدم العمل وما الحجم المتوقع؟ اذكر الوحدات؛ يمكن كتابة «غير محدد». يمكننا أيضاً مراجعة الرسم الخاص بك." },
  fr: { destination: "Ville / région et pays de livraison", destinationHint: "Ex. Austin, Texas, États-Unis", materialStudy: "Étude illustrative de matériaux ; ni photo d’atelier ni projet achevé.", drawingStudy: "Étude conceptuelle illustrative ; pas un plan de projet validé par le client.", role: "Votre rôle", email: "Email", company: "Entreprise / studio (facultatif)", budget: "Budget indicatif (facultatif)", optional: "Ajouter entreprise, téléphone, budget ou calendrier (facultatif)", budgetHint: "Montant et devise, ou à définir", roles: ["Designer / architecte / consultant en art", "Entrepreneur", "Fournisseur", "Promoteur / équipe achats", "Propriétaire privé", "Autre"], message: "Usage du projet et dimensions approximatives", messageHint: "Quel usage et quelles dimensions envisagez-vous ? Indiquez les unités ; « à définir » convient. Nous pouvons aussi étudier votre propre dessin." },
  es: { destination: "Ciudad / región y país de entrega", destinationHint: "Ej.: Austin, Texas, Estados Unidos", materialStudy: "Estudio ilustrativo de materiales; no es una foto de taller ni de un proyecto terminado.", drawingStudy: "Estudio conceptual ilustrativo; no es un plano de proyecto aprobado por el cliente.", role: "Su función", email: "Correo electrónico", company: "Empresa / estudio (opcional)", budget: "Presupuesto orientativo (opcional)", optional: "Añadir empresa, teléfono, presupuesto o fecha (opcional)", budgetHint: "Importe y moneda, o por definir", roles: ["Diseñador / arquitecto / consultor de arte", "Contratista", "Proveedor", "Promotor / equipo de compras", "Propietario particular", "Otra"], message: "Uso del proyecto y tamaño aproximado", messageHint: "¿Dónde se usará y qué tamaño tiene previsto? Incluya unidades; puede indicar «por definir». También podemos revisar su propio dibujo." },
  de: { destination: "Lieferort / Region und Land", destinationHint: "Z. B. Austin, Texas, USA", materialStudy: "Illustrative Materialstudie; kein Werkstattfoto oder Foto eines fertigen Projekts.", drawingStudy: "Illustrative Konzeptstudie; keine vom Kunden freigegebene Projektzeichnung.", role: "Ihre Rolle", email: "E-Mail", company: "Unternehmen / Studio (optional)", budget: "Budgetrahmen (optional)", optional: "Unternehmen, Telefon, Budget oder Termin ergänzen (optional)", budgetHint: "Betrag und Währung oder noch offen", roles: ["Designer / Architekt / Kunstberater", "Bauunternehmen", "Lieferant", "Projektentwickler / Einkaufsteam", "Privater Eigentümer", "Andere"], message: "Projektzweck und ungefähre Größe", messageHint: "Wo wird die Skulptur eingesetzt und welche Größe ist geplant? Bitte Einheiten angeben; „noch offen“ ist möglich. Wir prüfen auch Ihre eigene Zeichnung." },
};
