import { sculptureCatalog } from './sculptureCatalog.js';
import { studioIdentity } from './commissionProof.js';

export const catalogUi = {
  en: {
    nav: 'Collection', eyebrow: 'Custom sculpture directions', indexTitle: sculptureCatalog.h1, indexIntro: sculptureCatalog.intro,
    view: 'Explore this direction', request: 'Discuss this direction', back: 'Back to the collection',
    referenceLabel: 'Authorized visual reference', constructionLabel: 'Verified construction record',
    designHeading: 'Design and project parameters', reviewHeading: 'What we review with your team', faqHeading: 'Before you commission',
    relatedHeading: 'Related planning guides', moreHeading: 'Explore other directions', scopeHeading: 'Agree the scope before production',
    scopeBody: `${studioIdentity.en.capability} ${studioIdentity.en.delivery}`,
    briefLink: 'Send your project brief', formHeading: 'Your selected sculpture direction',
    formBody: 'This direction will be included with your brief. Share your site, dimensions and installation target; reference images are not fixed specifications.',
    previewTitle: 'Four directions. Your own site.', previewBody: 'Explore lobby, atrium, landscape and landmark starting points for a custom commission.',
    notFound: 'This sculpture direction was not found.', notFoundBody: 'Return to the collection to choose an available direction.',
  },
  zh: {
    nav: '雕塑系列', eyebrow: '定制雕塑方向', indexTitle: '找到方向，让它属于您的场地。',
    indexIntro: `${studioIdentity.zh.body} 四个定制雕塑起点。选择空间方向、查看证据，再告诉我们您的场地条件。设计、尺寸、饰面与交付范围均按项目确定。`,
    view: '查看这一方向', request: '讨论这一方向', back: '返回雕塑系列', referenceLabel: '获授权的视觉参考', constructionLabel: '已核实的施工记录',
    designHeading: '设计与项目参数', reviewHeading: '与项目团队共同评估', faqHeading: '委托前的问题', relatedHeading: '相关规划指南', moreHeading: '探索其他方向',
    scopeHeading: '制作前书面确认范围', scopeBody: `${studioIdentity.zh.capability} ${studioIdentity.zh.delivery}`,
    briefLink: '发送项目简报', formHeading: '您选择的雕塑方向', formBody: '这一方向将随简报一并发送。请提供场地、尺寸和目标安装时间；参考图片不是固定产品规格。',
    previewTitle: '四个方向，为您的场地而定。', previewBody: '从大堂、中庭、景观或地标方向开始定制项目。',
    notFound: '未找到这一雕塑方向。', notFoundBody: '请返回雕塑系列，选择现有方向。',
  },
  ar: {
    nav: 'المجموعة', eyebrow: 'اتجاهات نحت حسب الطلب', indexTitle: 'اختر اتجاهاً، وطوّره ليليق بموقعك.',
    indexIntro: `${studioIdentity.ar.body} أربع نقاط انطلاق لمشروع نحت مخصص. اختر التوجه المكاني، وراجع الأدلة، ثم أخبرنا عن موقعك. يُطوّر التصميم والأبعاد والتشطيب ونطاق التسليم لكل مشروع.`,
    view: 'استكشف هذا الاتجاه', request: 'ناقش هذا الاتجاه', back: 'العودة إلى المجموعة', referenceLabel: 'مرجع بصري مصرح بعرضه', constructionLabel: 'سجل تنفيذ موثّق',
    designHeading: 'التصميم ومعايير المشروع', reviewHeading: 'ما نراجعه مع فريقك', faqHeading: 'قبل بدء المشروع', relatedHeading: 'أدلة تخطيط ذات صلة', moreHeading: 'استكشف اتجاهات أخرى',
    scopeHeading: 'اتفقوا على النطاق قبل التصنيع', scopeBody: `${studioIdentity.ar.capability} ${studioIdentity.ar.delivery}`,
    briefLink: 'أرسل موجز مشروعك', formHeading: 'اتجاه النحت الذي اخترته', formBody: 'سيُرفق هذا الاتجاه بموجزك. شارك الموقع والأبعاد وموعد التركيب المستهدف؛ الصور المرجعية ليست مواصفات ثابتة.',
    previewTitle: 'أربعة اتجاهات، وموقعك الخاص.', previewBody: 'استكشف نقاط انطلاق للبهو أو الأتريوم أو المناظر الخارجية أو المعالم في مشروع مخصص.',
    notFound: 'لم نعثر على اتجاه النحت هذا.', notFoundBody: 'عد إلى المجموعة لاختيار اتجاه متاح.',
  },
  fr: {
    nav: 'Collection', eyebrow: 'Orientations de sculpture sur mesure', indexTitle: 'Trouvez une direction. Adaptez-la à votre lieu.',
    indexIntro: `${studioIdentity.fr.body} Quatre points de départ pour une sculpture sur mesure. Choisissez une orientation spatiale, examinez les éléments présentés et décrivez votre site. Le dessin, les dimensions, la finition et le périmètre de livraison sont définis pour chaque projet.`,
    view: 'Explorer cette direction', request: 'Discuter de cette direction', back: 'Retour à la collection', referenceLabel: 'Référence visuelle autorisée', constructionLabel: 'Suivi de chantier vérifié',
    designHeading: 'Conception et paramètres du projet', reviewHeading: 'Ce que nous étudions avec votre équipe', faqHeading: 'Avant de commander', relatedHeading: 'Guides de préparation associés', moreHeading: 'Explorer les autres directions',
    scopeHeading: 'Définir le périmètre avant fabrication', scopeBody: `${studioIdentity.fr.capability} ${studioIdentity.fr.delivery}`,
    briefLink: 'Envoyer votre cahier des charges', formHeading: 'Votre direction de sculpture', formBody: 'Cette direction accompagnera votre demande. Précisez le site, les dimensions et la date de pose souhaitée ; les images de référence ne sont pas des spécifications fixes.',
    previewTitle: 'Quatre directions. Votre propre lieu.', previewBody: 'Explorez des pistes pour un hall, un atrium, un paysage ou un repère monumental sur mesure.',
    notFound: 'Cette direction de sculpture est introuvable.', notFoundBody: 'Revenez à la collection pour choisir une direction disponible.',
  },
  es: {
    nav: 'Colección', eyebrow: 'Direcciones de escultura a medida', indexTitle: 'Encuentre una dirección. Adáptela a su espacio.',
    indexIntro: `${studioIdentity.es.body} Cuatro puntos de partida para una escultura a medida. Elija un enfoque espacial, revise las evidencias y cuéntenos sobre su ubicación. El diseño, las dimensiones, el acabado y el alcance de entrega se desarrollan para cada proyecto.`,
    view: 'Explorar esta dirección', request: 'Consultar esta dirección', back: 'Volver a la colección', referenceLabel: 'Referencia visual autorizada', constructionLabel: 'Registro de construcción verificado',
    designHeading: 'Diseño y parámetros del proyecto', reviewHeading: 'Qué revisamos con su equipo', faqHeading: 'Antes de encargar', relatedHeading: 'Guías de planificación relacionadas', moreHeading: 'Explorar otras direcciones',
    scopeHeading: 'Acordar el alcance antes de fabricar', scopeBody: `${studioIdentity.es.capability} ${studioIdentity.es.delivery}`,
    briefLink: 'Enviar el resumen de su proyecto', formHeading: 'La dirección de escultura que eligió', formBody: 'Esta dirección se incluirá en su consulta. Comparta la ubicación, las dimensiones y la fecha prevista de instalación; las referencias visuales no son especificaciones fijas.',
    previewTitle: 'Cuatro direcciones. Su propio espacio.', previewBody: 'Explore opciones para vestíbulos, atrios, paisajes o hitos en un proyecto a medida.',
    notFound: 'No encontramos esta dirección de escultura.', notFoundBody: 'Vuelva a la colección para elegir una dirección disponible.',
  },
  de: {
    nav: 'Kollektion', eyebrow: 'Skulpturen nach Maß', indexTitle: 'Finden Sie eine Richtung. Gestalten Sie sie für Ihren Ort.',
    indexIntro: `${studioIdentity.de.body} Vier Ausgangspunkte für eine individuelle Skulptur. Wählen Sie eine räumliche Richtung, prüfen Sie die Nachweise und beschreiben Sie Ihren Standort. Entwurf, Maße, Oberfläche und Lieferumfang werden für jedes Projekt entwickelt.`,
    view: 'Diese Richtung erkunden', request: 'Diese Richtung besprechen', back: 'Zurück zur Kollektion', referenceLabel: 'Zur Darstellung freigegebene Referenz', constructionLabel: 'Verifizierte Baudokumentation',
    designHeading: 'Entwurf und Projektparameter', reviewHeading: 'Was wir mit Ihrem Team prüfen', faqHeading: 'Vor der Beauftragung', relatedHeading: 'Passende Planungsleitfäden', moreHeading: 'Weitere Richtungen erkunden',
    scopeHeading: 'Umfang vor der Fertigung vereinbaren', scopeBody: `${studioIdentity.de.capability} ${studioIdentity.de.delivery}`,
    briefLink: 'Projektbeschreibung senden', formHeading: 'Ihre gewählte Skulpturenrichtung', formBody: 'Diese Richtung wird Ihrer Anfrage beigefügt. Nennen Sie Standort, Maße und gewünschten Montagetermin; Referenzbilder sind keine festen Produktspezifikationen.',
    previewTitle: 'Vier Richtungen. Ihr eigener Ort.', previewBody: 'Entdecken Sie Ausgangspunkte für eine individuelle Lobby-, Atrium-, Landschafts- oder Landmarkenskulptur.',
    notFound: 'Diese Skulpturenrichtung wurde nicht gefunden.', notFoundBody: 'Kehren Sie zur Kollektion zurück und wählen Sie eine verfügbare Richtung.',
  },
};

const translations = {
  es: {
    'mirror-lobby-sculpture': {
      title: 'Escultura espejo para vestíbulo o espacio con agua', category: 'Vestíbulo / elemento acuático',
      intro: 'Un foco reflectante necesita espacio. Comience por la circulación de los huéspedes, el borde del agua y la arquitectura; después desarrolle una escultura propia para su vestíbulo.',
      disclosure: 'Referencias de espacios comerciales con exhibición autorizada, no proyectos hoteleros terminados de WEIERYANG. El uso hotelero es una aplicación propuesta; las imágenes orientan un diseño original para el lugar.',
      images: [
        { alt: 'Escultura reflectante en forma de ballena, esferas suspendidas y estanque en un interior comercial acristalado', caption: 'Referencia comercial: vista completa de la escultura, el estanque y la circulación circundante.' },
        { alt: 'Dos vistas proporcionadas de una instalación reflectante con forma de ballena y su entorno arquitectónico', caption: 'Dos referencias de una misma disposición espacial para estudiar reflejos, distancia de observación y borde del agua.' },
      ],
      specification: [['Dirección de diseño', 'Foco escultórico reflectante; forma original desarrollada para el lugar.'], ['Material y acabado', 'Dirección en acero inoxidable; grado y acabado espejo o cepillado acordados mediante muestras.'], ['Dimensiones', 'Según el lugar. Comparta un plano en pies/pulgadas o unidades métricas; no se presupone un tamaño estándar.']],
      review: ['Rutas de huéspedes, espacios libres accesibles y superficie ocupada.', 'Interfaces del elemento acuático, acceso de limpieza y exposición a salpicaduras.', 'Reflejos y deslumbramiento con la iluminación real del proyecto.'],
      faq: [['¿Esta dirección funciona sin un elemento acuático?', 'Sí, puede evaluarse una instalación en un vestíbulo seco. La base, la circulación, la iluminación y el mantenimiento se desarrollarían para ese entorno.'], ['¿Cómo se establece el precio?', 'La propuesta se prepara tras revisar el lugar, el diseño original, la escala, el acabado, la estructura, el destino y el alcance de instalación. Las referencias no tienen un precio de producto fijo.']],
      relatedLabels: ['Guía de planificación para vestíbulos', 'Acabado espejo en acero inoxidable', 'Servicio para hoteles y resorts'],
    },
    'vertical-atrium-sculpture': {
      title: 'Escultura vertical para un atrio de varios niveles', category: 'Atrio / hito interior',
      intro: 'Una escultura de atrio se observa desde varios pisos. Desarrolle su silueta y escala con el equipo del edificio, considerando juntos los espacios libres, las interfaces estructurales y el acceso de instalación.',
      disclosure: 'Referencias autorizadas de atrios comerciales, no proyectos hoteleros terminados de WEIERYANG. La forma, el sistema de fijación y los materiales fotografiados no se ofrecen como especificaciones verificadas ni como una réplica.',
      images: [
        { alt: 'Instalación vertical esbelta dentro de un atrio comercial de varios niveles', caption: 'Referencia de atrio comercial: composición vertical completa en relación con los pisos circundantes.' },
        { alt: 'Parte inferior de una instalación de atrio y espacio peatonal adyacente', caption: 'Vista de referencia para estudiar la base y el espacio peatonal libre; los detalles de fijación no están verificados.' },
        { alt: 'Instalación de atrio vista entre pisos y barandillas interiores', caption: 'Referencia de las líneas de visión entre pisos y del contexto arquitectónico.' },
      ],
      specification: [['Dirección de diseño', 'Composición vertical original coordinada con la arquitectura del atrio.'], ['Material y acabado', 'Seleccionados tras revisar forma, iluminación, mantenimiento y requisitos estructurales.'], ['Dimensiones', 'Definidas según niveles, altura libre y distancias de observación; se aceptan pies/pulgadas o unidades métricas.']],
      review: ['Vistas desde la entrada, los pisos superiores y las principales rutas de huéspedes.', 'Ubicaciones de apoyo, revisión estructural local e interfaces del edificio.', 'Ruta de izado, zonas de montaje, protección y acceso para mantenimiento futuro.'],
      faq: [['¿Pueden evaluar un atrio existente?', 'Sí. Comparta planos, una sección o medidas de altura libre, fotografías y la ventana prevista de instalación. El acceso y la protección de las zonas ocupadas forman parte de la revisión inicial.'], ['¿Se incluye una instalación suspendida?', 'El soporte se desarrolla para cada diseño y edificio. Una fotografía no demuestra un sistema de suspensión verificado; las responsabilidades estructurales y las aprobaciones locales deben acordarse en la propuesta.']],
      relatedLabels: ['Guía de planificación de esculturas de atrio', 'Proceso de escultura a medida', 'Servicio para hoteles y resorts'],
    },
    'tree-canopy-sculpture': {
      title: 'Esculturas de árbol y dosel para el paisaje de acceso', category: 'Llegada / paisaje',
      intro: 'Deje que la secuencia de llegada guíe la escultura. Las referencias de árbol y dosel ofrecen distintas formas de crear un foco, enmarcar el espacio peatonal y conectar la pieza con el paisaje.',
      disclosure: 'Referencias paisajísticas autorizadas de obras diferentes, no varias vistas de un producto. El aspecto dorado no confirma el grado del metal ni el recubrimiento. No se presentan como proyectos hoteleros de WEIERYANG.',
      images: [
        { alt: 'Escultura con forma de árbol y aspecto dorado junto al pavimento y un edificio en construcción', caption: 'Referencia de árbol: vista completa de la silueta ramificada y del entorno de llegada.' },
        { alt: 'Dos referencias paisajísticas distintas con forma de dosel y superficies dorada y roja', caption: 'Dos doseles diferentes para comparar ritmo espacial y dirección de acabado.' },
      ],
      specification: [['Dirección de diseño', 'Formas originales de árbol o dosel desarrolladas con el paisaje y las vistas de aproximación.'], ['Material y acabado', 'Metal y sistema de recubrimiento confirmados tras revisar la exposición y aprobar muestras.'], ['Dimensiones', 'Superficie y altura propias del proyecto, coordinadas con las rutas peatonales y vehiculares.']],
      review: ['Vistas de llegada, espacios peatonales libres e interfaces con pavimento y paisaje.', 'Exposición al viento, drenaje, condiciones de corrosión y mantenimiento.', 'Responsabilidades de cimentación, anclaje, acceso de entrega y montaje.'],
      faq: [['¿Pueden desarrollar el color y la silueta para nuestro paisaje?', 'Sí. Puede desarrollarse un diseño original y un acabado en torno a la arquitectura y la vegetación. Las referencias orientan la conversación; no prometen duplicar una obra existente.'], ['¿Un dosel escultórico puede dar refugio?', 'La protección de la lluvia o la sombra utilizable son requisitos de diseño independientes. Deben evaluarse expresamente junto con cargas, drenaje, seguridad y aprobaciones locales; las referencias decorativas no demuestran esas funciones.']],
      relatedLabels: ['Resumen del lugar para esculturas de llegada', 'Servicio de escultura paisajística', 'Selección de acero para exteriores'],
    },
    'bird-landmark-sculpture': {
      title: 'Hito escultórico de ave en acero inoxidable', category: 'Espacio público / hito',
      intro: 'Un hito comienza con una forma y un plan de entrega creíble. Nuestro registro de construcción en Oriente Medio ofrece una base real para hablar de un ave a medida, el montaje por segmentos y la coordinación de instalación.',
      disclosure: 'Fotografías verificadas de la fase de construcción en un espacio público de Oriente Medio. Documentan montaje e instalación, no un hotel terminado ni un proyecto estadounidense. Los nuevos diseños y alcances de entrega requieren una revisión independiente.',
      images: [
        { alt: 'Hito de acero inoxidable con forma de ave durante su instalación en un espacio público de Oriente Medio', caption: 'Registro de construcción verificado en Oriente Medio: instalación en curso.' },
        { alt: 'Montaje estructural por segmentos del hito de ave en acero inoxidable durante la construcción', caption: 'Registro de la fase de montaje estructural por segmentos; no es una fotografía de obra terminada.' },
        { alt: 'Alineación de elementos repetidos de ala en acero inoxidable durante la instalación del hito', caption: 'Registro de construcción: alineación e instalación de los elementos repetidos del ala.' },
      ],
      specification: [['Dirección de diseño', 'Hito original con forma de ave y geometría y estructura desarrolladas para el lugar.'], ['Material y acabado', 'Acero inoxidable; grado, acabado y requisitos de exposición confirmados para el nuevo proyecto.'], ['Dimensiones', 'Según el lugar; se necesitan planos, zona de base y acceso de izado antes de fijar el alcance.']],
      review: ['Vistas principales, escala prevista y relación con el espacio público.', 'Coordinación del diseño estructural, cimentaciones y aprobaciones locales.', 'Segmentos de transporte, plan de izado, acceso al lugar y responsabilidades de instalación.'],
      faq: [['¿Qué verifican estas fotografías?', 'Verifican la fase de construcción registrada en un espacio público de Oriente Medio, incluidos montaje estructural e instalación. No acreditan un hotel estadounidense terminado, especificaciones fijas ni el precio de un nuevo proyecto.'], ['¿Qué apoyo de entrega pueden ofrecer?', 'WEIERYANG puede coordinar diseño escultórico, desarrollo estructural, fabricación, embalaje de exportación y orientación para instalación internacional. Los trabajos de obra, la ingeniería local, el izado y las responsabilidades de los instaladores se definen en la propuesta.']],
      relatedLabels: ['Registro de construcción en Oriente Medio', 'Evidencias de proyectos', 'Factores de costo de grandes esculturas exteriores'],
    },
  },
  de: {
    'mirror-lobby-sculpture': {
      title: 'Spiegelnde Skulptur für Lobby oder Wasseranlage', category: 'Lobby / Wasseranlage',
      intro: 'Ein reflektierender Blickfang braucht Raum. Prüfen Sie zuerst Gästewege, Wasserkante und umgebende Architektur, und entwickeln Sie dann eine eigenständige Skulptur für Ihre Lobby.',
      disclosure: 'Zur Darstellung freigegebene Referenzen aus gewerblichen Räumen, keine fertiggestellten Hotelaufträge von WEIERYANG. Die Hotelnutzung ist ein Vorschlag; die Bilder unterstützen einen eigenständigen Entwurf für den Standort.',
      images: [
        { alt: 'Reflektierende Skulptur in Walform, schwebende Kugeln und Wasserbecken in einem verglasten gewerblichen Innenraum', caption: 'Gewerbliche Raumreferenz: Gesamtansicht der Skulptur, des Beckens und der umgebenden Wege.' },
        { alt: 'Zwei bereitgestellte Ansichten einer reflektierenden Installation in Walform mit architektonischem Umfeld', caption: 'Zwei Referenzansichten derselben räumlichen Anordnung zur Prüfung von Reflexionen, Betrachtungsabstand und Wasserkante.' },
      ],
      specification: [['Entwurfsrichtung', 'Reflektierender skulpturaler Blickfang; eigenständige Form für den Standort.'], ['Material und Oberfläche', 'Edelstahl als Richtung; Stahlsorte und spiegelnde oder gebürstete Oberfläche werden anhand von Mustern vereinbart.'], ['Maße', 'Für den Standort festgelegt. Bitte einen Plan in Fuß/Zoll oder metrischen Einheiten senden; es wird keine Standardgröße vorausgesetzt.']],
      review: ['Gästewege, barrierefreie Durchgänge und beanspruchte Grundfläche.', 'Schnittstellen zur Wasseranlage, Reinigungszugang und Spritzwasserbelastung.', 'Reflexionen und Blendung unter der tatsächlichen Projektbeleuchtung.'],
      faq: [['Funktioniert diese Richtung auch ohne Wasseranlage?', 'Ja, eine Installation in einer trockenen Lobby kann geprüft werden. Sockel, Gästewege, Beleuchtung und Wartung werden für diesen Ort entwickelt.'], ['Wie wird der Preis ermittelt?', 'Ein Angebot folgt auf die Prüfung von Standort, eigenständigem Entwurf, Maßstab, Oberfläche, Tragwerk, Zielort und Montageumfang. Diese Referenzbilder stehen für keinen festen Produktpreis.']],
      relatedLabels: ['Planungsleitfaden für Lobbyskulpturen', 'Spiegelnde Edelstahloberfläche', 'Service für Hotels und Resorts'],
    },
    'vertical-atrium-sculpture': {
      title: 'Vertikale Skulptur für ein mehrgeschossiges Atrium', category: 'Atrium / Blickfang im Innenraum',
      intro: 'Eine Atriumskulptur ist aus mehreren Geschossen gleichzeitig sichtbar. Entwickeln Sie Silhouette und Maßstab mit dem Gebäudeteam und prüfen Sie Freiräume, Tragwerksschnittstellen und Montagezugang gemeinsam.',
      disclosure: 'Freigegebene Referenzen gewerblicher Atrien, keine fertiggestellten Hotelaufträge von WEIERYANG. Fotografierte Form, Befestigung und Materialien werden weder als verifizierte Spezifikationen noch als Replik angeboten.',
      images: [
        { alt: 'Schlanke vertikale Installation in einem mehrgeschossigen gewerblichen Atrium', caption: 'Gewerbliche Atriumreferenz: vollständige vertikale Komposition im Verhältnis zu den umliegenden Geschossen.' },
        { alt: 'Unterer Bereich einer Atriuminstallation und angrenzender Fußgängerraum', caption: 'Referenz zur Besprechung von Sockelzone und freiem Durchgang; Befestigungsdetails sind nicht verifiziert.' },
        { alt: 'Atriuminstallation mit Blick über Geschosse und innere Brüstungen', caption: 'Referenzansicht für Sichtachsen zwischen Geschossen und den architektonischen Zusammenhang.' },
      ],
      specification: [['Entwurfsrichtung', 'Eigenständige vertikale Komposition, abgestimmt auf die Atriumarchitektur.'], ['Material und Oberfläche', 'Auswahl nach Prüfung von Form, Beleuchtung, Wartung und Tragwerksanforderungen.'], ['Maße', 'Nach Geschossebenen, lichter Höhe und Betrachtungsabständen; Fuß/Zoll oder metrische Einheiten möglich.']],
      review: ['Ansichten vom Eingang, aus oberen Geschossen und von den wichtigsten Gästewegen.', 'Auflagerpositionen, örtliche Tragwerksprüfung und Gebäudeschnittstellen.', 'Hubweg, Montagebereiche, Schutzmaßnahmen und spätere Wartungszugänge.'],
      faq: [['Können Sie ein bestehendes Atrium prüfen?', 'Ja. Senden Sie Grundrisse, einen Schnitt oder lichte Höhen, Fotos und das gewünschte Montagefenster. Zugang und Schutz der genutzten Bereiche gehören zur ersten Prüfung.'], ['Ist eine abgehängte Installation enthalten?', 'Die Traglösung wird für jeden Entwurf und jedes Gebäude entwickelt. Ein Foto belegt kein verifiziertes Abhängesystem; Tragwerkszuständigkeiten und örtliche Freigaben müssen im Angebot vereinbart werden.']],
      relatedLabels: ['Planungsleitfaden für Atriumskulpturen', 'Ablauf einer individuellen Skulptur', 'Service für Hotels und Resorts'],
    },
    'tree-canopy-sculpture': {
      title: 'Baum- und Schirmskulpturen für die Ankunftslandschaft', category: 'Ankunft / Landschaft',
      intro: 'Lassen Sie den Ankunftsweg die Skulptur prägen. Baum- und Schirmformen zeigen verschiedene Möglichkeiten, einen Blickfang zu setzen, Fußgängerräume zu fassen und ein Werk mit seiner Landschaft zu verbinden.',
      disclosure: 'Freigegebene Landschaftsreferenzen verschiedener Werke, keine mehreren Ansichten eines Produkts. Ein Goldton bestätigt weder Metallsorte noch Beschichtung. Die Bilder werden nicht als Hotelaufträge von WEIERYANG dargestellt.',
      images: [
        { alt: 'Goldfarbene Skulptur in Baumform neben Pflasterung und einem Gebäude im Bau', caption: 'Baumreferenz: Gesamtansicht der verzweigten Silhouette und des Ankunftsbereichs.' },
        { alt: 'Zwei getrennte Landschaftsreferenzen in Schirmform mit goldfarbener und roter Oberfläche', caption: 'Zwei unterschiedliche Schirmreferenzen zum Vergleich von räumlichem Rhythmus und Oberflächenrichtung.' },
      ],
      specification: [['Entwurfsrichtung', 'Eigenständige Baum- oder Schirmformen, entwickelt mit Landschaft und Annäherungsansichten.'], ['Material und Oberfläche', 'Metall und Beschichtungssystem nach Prüfung der Beanspruchung und Musterfreigabe festlegen.'], ['Maße', 'Projektbezogene Grundfläche und Höhe, abgestimmt auf Fußgänger- und Fahrzeugwege.']],
      review: ['Ankunftsansichten, freie Fußgängerwege sowie Schnittstellen zu Pflasterung und Landschaft.', 'Windbelastung, Entwässerung, Korrosionsbedingungen und Pflege.', 'Zuständigkeiten für Fundamente, Verankerung, Lieferzugang und Montage.'],
      faq: [['Können Farbe und Silhouette für unsere Landschaft entwickelt werden?', 'Ja. Ein eigenständiger Entwurf und eine Oberfläche können auf Architektur und Bepflanzung abgestimmt werden. Referenzbilder dienen dem Gespräch und sind kein Versprechen, ein vorhandenes Werk zu kopieren.'], ['Kann eine Schirmskulptur Schutz bieten?', 'Wetterschutz oder nutzbarer Schatten sind eigene Entwurfsanforderungen. Sie müssen ausdrücklich mit Lasten, Entwässerung, Sicherheit und örtlichen Freigaben geprüft werden; dekorative Referenzen belegen diese Funktionen nicht.']],
      relatedLabels: ['Standortbeschreibung für Ankunftsskulpturen', 'Service für Landschaftsskulpturen', 'Edelstahlauswahl für den Außenbereich'],
    },
    'bird-landmark-sculpture': {
      title: 'Landmarkenskulptur in Vogelform aus Edelstahl', category: 'Öffentlicher Ort / Landmarke',
      intro: 'Eine Landmarke beginnt mit einer Form und einem belastbaren Lieferplan. Unsere Baudokumentation aus dem Nahen Osten bietet eine konkrete Grundlage für eine individuelle Vogelskulptur, segmentierte Montage und die Koordination vor Ort.',
      disclosure: 'Verifizierte Fotos der Bauphase an einem öffentlichen Ort im Nahen Osten. Sie zeigen Zusammenbau und Montage, kein fertiggestelltes Hotelprojekt und keinen US-Auftrag. Neue Entwürfe und Lieferumfänge erfordern eine eigene Projektprüfung.',
      images: [
        { alt: 'Landmarkenskulptur in Vogelform aus Edelstahl während der Montage an einem öffentlichen Ort im Nahen Osten', caption: 'Verifizierte Baudokumentation aus dem Nahen Osten: Montage vor Ort im Gange.' },
        { alt: 'Segmentierter Zusammenbau des Tragwerks der Vogellandmarke aus Edelstahl während der Bauphase', caption: 'Bauphasendokumentation der segmentierten Tragwerksmontage; kein Foto eines fertiggestellten Projekts.' },
        { alt: 'Ausrichten wiederkehrender Edelstahlflügelelemente während der Montage der Landmarke', caption: 'Bauphasendokumentation: Ausrichtung und Montage der wiederkehrenden Flügelelemente.' },
      ],
      specification: [['Entwurfsrichtung', 'Eigenständige Vogellandmarke mit für den Standort entwickelter Geometrie und Struktur.'], ['Material und Oberfläche', 'Edelstahl; Stahlsorte, Oberfläche und Beanspruchung werden für das neue Projekt bestätigt.'], ['Maße', 'Standortbezogen; vor Festlegung des Umfangs werden Zeichnungen, Sockelzone und Hubzugang benötigt.']],
      review: ['Hauptansichten, gewünschter Maßstab und Beziehung zum öffentlichen Raum.', 'Koordination des Tragwerksentwurfs, Fundamente und örtliche Freigaben.', 'Versandsegmente, Hubplan, Standortzugang und Montagezuständigkeiten.'],
      faq: [['Was belegen diese Fotos?', 'Sie belegen die dokumentierte Bauphase an einem öffentlichen Ort im Nahen Osten, einschließlich Tragwerkszusammenbau und Montage. Sie belegen weder ein fertiggestelltes US-Hotelprojekt noch feste Produktspezifikationen oder den Preis eines neuen Projekts.'], ['Welche Unterstützung bei der Lieferung ist möglich?', 'WEIERYANG kann Skulpturenentwurf, Tragwerksentwicklung, Fertigung, Exportverpackung und Montageanleitung im Ausland koordinieren. Baustellenarbeiten, örtliche Ingenieurleistungen, Hebearbeiten und Zuständigkeiten der Monteure werden im Projektangebot festgelegt.']],
      relatedLabels: ['Baudokumentation aus dem Nahen Osten', 'Projektnachweise', 'Kostenfaktoren großer Außenskulpturen'],
    },
  },
  ar: {
    'mirror-lobby-sculpture': {
      title: 'منحوتة عاكسة للبهو أو العنصر المائي', category: 'بهو / عنصر مائي',
      intro: 'تحتاج نقطة التركيز العاكسة إلى مساحة مناسبة. ابدأ بحركة الضيوف وحافة الماء والعمارة المحيطة، ثم طوّر منحوتة مميزة لبهوك.',
      disclosure: 'مراجع لمساحات تجارية مصرح بعرضها، وليست مشاريع فندقية مكتملة من WEIERYANG. الاستخدام الفندقي مقترح؛ وتدعم الصور تطوير تصميم أصلي خاص بالموقع.',
      images: [
        { alt: 'منحوتة عاكسة بشكل حوت وكرات معلقة وحوض ماء داخل مساحة تجارية زجاجية', caption: 'مرجع لمساحة تجارية: مشهد كامل للمنحوتة وحوض الماء ومسارات الحركة المحيطة.' },
        { alt: 'صورتان مرجعيتان مقدمتان لتركيب عاكس بشكل حوت وسياقه المعماري', caption: 'منظوران مرجعيان لترتيب مكاني واحد لدراسة الانعكاسات ومسافة المشاهدة وحافة الماء.' },
      ],
      specification: [['اتجاه التصميم', 'نقطة تركيز نحتية عاكسة؛ يُطوّر الشكل الأصلي للموقع.'], ['المادة والتشطيب', 'اتجاه من الفولاذ المقاوم للصدأ؛ تُعتمد الدرجة والتشطيبات المرآتية أو المصقولة بالفرشاة عبر العينات.'], ['الأبعاد', 'خاصة بالموقع. أرسل مخططاً بالأقدام والبوصات أو بالنظام المتري؛ لا يُفترض مقاس قياسي.']],
      review: ['مسارات الضيوف والخلوص اللازم لإتاحة الوصول والمساحة المشغولة.', 'واجهات العنصر المائي ومسارات التنظيف والتعرض لرذاذ الماء.', 'الانعكاسات والوهج تحت إضاءة المشروع الفعلية.'],
      faq: [['هل يصلح هذا الاتجاه دون عنصر مائي؟', 'نعم، يمكن دراسة تركيب في بهو جاف. تُطوّر القاعدة وحركة الضيوف والإضاءة وخطة الصيانة لهذا الموقع.'], ['كيف يُحدد السعر؟', 'يُعد العرض بعد مراجعة الموقع والتصميم الأصلي والحجم والتشطيب والهيكل والوجهة ونطاق التركيب. لا تمثل الصور المرجعية منتجاً بسعر ثابت.']],
      relatedLabels: ['دليل تخطيط منحوتة البهو', 'تشطيب الفولاذ المقاوم للصدأ المرآتي', 'خدمات الفنادق والمنتجعات'],
    },
    'vertical-atrium-sculpture': {
      title: 'منحوتة رأسية لأتريوم متعدد الطوابق', category: 'أتريوم / معلم داخلي',
      intro: 'تُشاهد منحوتة الأتريوم من عدة طوابق في الوقت نفسه. طوّر محيطها وحجمها مع فريق المبنى، مع دراسة الخلوص والواجهات الإنشائية ومسارات التركيب معاً.',
      disclosure: 'مراجع لأتريوم تجاري مصرح بعرضها، وليست مشاريع فندقية مكتملة من WEIERYANG. الشكل ونظام التثبيت والمواد المصوّرة ليست مواصفات موثقة معروضة للبيع ولا منتجاً للاستنساخ.',
      images: [
        { alt: 'تركيب رأسي نحيل داخل أتريوم تجاري متعدد الطوابق', caption: 'مرجع لأتريوم تجاري: التكوين الرأسي الكامل وعلاقته بالطوابق المحيطة.' },
        { alt: 'الجزء السفلي من تركيب الأتريوم ومساحة المشاة المجاورة', caption: 'منظور مرجعي لمناقشة منطقة القاعدة وخلوص المشاة؛ تفاصيل التثبيت غير متحققة.' },
        { alt: 'تركيب الأتريوم كما يُرى عبر الطوابق والدرابزين الداخلي', caption: 'منظور مرجعي لخطوط الرؤية بين الطوابق والسياق المعماري.' },
      ],
      specification: [['اتجاه التصميم', 'تكوين رأسي أصلي يُنسق مع عمارة الأتريوم.'], ['المادة والتشطيب', 'يُختاران بعد مراجعة الشكل والإضاءة والصيانة والمتطلبات الإنشائية.'], ['الأبعاد', 'تُحدد من مناسيب الطوابق والارتفاع الصافي ومسافات المشاهدة؛ تُقبل الأقدام والبوصات أو الوحدات المترية.']],
      review: ['المشاهد من المدخل والطوابق العليا ومسارات الضيوف الرئيسية.', 'مواقع الدعم والمراجعة الإنشائية المحلية وواجهات المبنى.', 'مسار الرفع ومناطق التجميع والحماية والوصول للصيانة لاحقاً.'],
      faq: [['هل يمكن تقييم أتريوم قائم؟', 'نعم. أرسل المخططات وقطاعاً أو قياسات الارتفاع الصافي والصور ونافذة التركيب المطلوبة. تشمل المراجعة الأولية الوصول وحماية المناطق المستخدمة.'], ['هل يشمل ذلك تركيباً معلقاً؟', 'يُطوّر أسلوب الدعم لكل تصميم ومبنى. لا تثبت الصورة نظام تعليق موثّقاً؛ يجب الاتفاق على المسؤوليات الإنشائية والاعتمادات المحلية في العرض.']],
      relatedLabels: ['دليل تخطيط منحوتة الأتريوم', 'عملية النحت حسب الطلب', 'خدمات الفنادق والمنتجعات'],
    },
    'tree-canopy-sculpture': {
      title: 'منحوتات شجرية ومظلية لمساحة الوصول', category: 'وصول / مناظر خارجية',
      intro: 'دع تسلسل الوصول يوجّه المنحوتة. توفر مراجع الأشجار والأشكال المظلية طرقاً مختلفة لصنع نقطة تركيز وتأطير مساحة المشاة وربط العمل بالمناظر المحيطة.',
      disclosure: 'مراجع خارجية مصرح بعرضها لأعمال مختلفة، وليست زوايا لمنتج واحد. المظهر الذهبي لا يثبت درجة المعدن أو الطلاء. ولا تُعرض هذه الصور كمشاريع فندقية لـ WEIERYANG.',
      images: [
        { alt: 'منحوتة بشكل شجرة ذات مظهر ذهبي قرب رصف ومبنى قيد الإنشاء', caption: 'مرجع لشكل شجري: مشهد كامل للتفرعات وسياق مساحة الوصول.' },
        { alt: 'مرجعان منفصلان لمنحوتات مظلية خارجية بسطحين ذهبي وأحمر', caption: 'مرجعان مظليان مختلفان لمقارنة الإيقاع المكاني واتجاه التشطيب.' },
      ],
      specification: [['اتجاه التصميم', 'أشكال أصلية شجرية أو مظلية تُطوّر مع المناظر الخارجية ومشاهد الاقتراب.'], ['المادة والتشطيب', 'يُحدد المعدن ونظام الطلاء بعد مراجعة التعرض واعتماد العينات.'], ['الأبعاد', 'مساحة وارتفاع خاصان بالمشروع، يُنسقان مع مسارات المشاة والمركبات.']],
      review: ['مشاهد الوصول وخلوص المشاة وواجهات الرصف والمناظر الخارجية.', 'التعرض للرياح والتصريف وظروف التآكل والصيانة.', 'مسؤوليات الأساسات والتثبيت ومسار التسليم والتجميع.'],
      faq: [['هل يمكن تطوير اللون والشكل لمناظرنا الخارجية؟', 'نعم. يمكن تطوير تصميم أصلي وتشطيب حول العمارة والنباتات. الصور المرجعية توجه النقاش ولا تعد بتكرار عمل موجود.'], ['هل توفر المنحوتة المظلية مأوى؟', 'الحماية من المطر أو الظل القابل للاستخدام متطلب تصميم مستقل. يجب تقييمه صراحةً مع الأحمال والتصريف والسلامة والاعتمادات المحلية؛ المراجع الزخرفية لا تثبت هذه الوظائف.']],
      relatedLabels: ['موجز موقع منحوتة الوصول', 'خدمات النحت الخارجي', 'اختيار الفولاذ للاستخدام الخارجي'],
    },
    'bird-landmark-sculpture': {
      title: 'منحوتة معلم بشكل طائر من الفولاذ المقاوم للصدأ', category: 'موقع عام / معلم',
      intro: 'يبدأ المعلم بشكل وخطة تسليم موثوقة. يوفر سجل التنفيذ في الشرق الأوسط نقطة انطلاق عملية لمناقشة منحوتة طائر مخصصة والتجميع المجزأ وتنسيق التركيب بالموقع.',
      disclosure: 'صور موثّقة لمرحلة التنفيذ في موقع عام بالشرق الأوسط. تسجل أعمال التجميع والتركيب، وليست مشروعاً فندقياً مكتملاً أو تكليفاً أمريكياً. تتطلب التصاميم ونطاقات التسليم الجديدة مراجعة مستقلة.',
      images: [
        { alt: 'معلم نحتي بشكل طائر من الفولاذ المقاوم للصدأ أثناء تركيبه بموقع عام في الشرق الأوسط', caption: 'سجل تنفيذ موثّق في الشرق الأوسط: التركيب بالموقع جارٍ.' },
        { alt: 'تجميع الهيكل المجزأ لمعلم الطائر من الفولاذ المقاوم للصدأ أثناء التنفيذ', caption: 'سجل مرحلة التنفيذ لتجميع الهيكل المجزأ، وليس صورة مشروع مكتمل.' },
        { alt: 'محاذاة عناصر جناح متكررة من الفولاذ المقاوم للصدأ أثناء تركيب المعلم', caption: 'سجل مرحلة التنفيذ: محاذاة عناصر الجناح المتكررة وتركيبها.' },
      ],
      specification: [['اتجاه التصميم', 'معلم أصلي بشكل طائر، تُطوّر هندسته وشكله الإنشائي للموقع.'], ['المادة والتشطيب', 'فولاذ مقاوم للصدأ؛ تُحدد الدرجة والتشطيب ومتطلبات التعرض للمشروع الجديد.'], ['الأبعاد', 'خاصة بالموقع؛ تلزم الرسومات ومنطقة القاعدة ومسار الرفع قبل تثبيت النطاق.']],
      review: ['المشاهد الرئيسية والحجم المستهدف والعلاقة بالمساحة العامة.', 'تنسيق التصميم الإنشائي والأساسات والاعتمادات المحلية.', 'قطاعات الشحن وخطة الرفع والوصول للموقع ومسؤوليات التركيب.'],
      faq: [['ماذا توثّق هذه الصور؟', 'توثّق مرحلة التنفيذ المسجلة في موقع عام بالشرق الأوسط، بما فيها تجميع الهيكل والتركيب. ولا تثبت مشروعاً فندقياً أمريكياً مكتملاً أو مواصفات منتج ثابتة أو سعر مشروع جديد.'], ['ما دعم التسليم المتاح؟', 'يمكن لـ WEIERYANG تنسيق تصميم المنحوتة والتطوير الإنشائي والتصنيع والتغليف للتصدير وإرشادات التركيب خارج البلاد. تُحدد أعمال الموقع والهندسة المحلية والرفع ومسؤوليات المنفذين في عرض المشروع.']],
      relatedLabels: ['سجل التنفيذ في الشرق الأوسط', 'أدلة المشروع', 'عوامل تكلفة المنحوتات الخارجية الكبيرة'],
    },
  },
  fr: {
    'mirror-lobby-sculpture': {
      title: 'Sculpture miroir pour un hall ou un bassin', category: 'Hall / élément aquatique',
      intro: 'Un point focal réfléchissant a besoin d’espace. Étudiez d’abord la circulation des clients, le bord de l’eau et l’architecture, puis développez une sculpture propre à votre hall.',
      disclosure: 'Références commerciales dont la présentation est autorisée, et non projets hôteliers achevés par WEIERYANG. L’usage hôtelier est proposé ; ces images nourrissent une création originale adaptée au site.',
      images: [
        { alt: 'Sculpture réfléchissante en forme de baleine, sphères suspendues et bassin dans un intérieur commercial vitré', caption: 'Référence commerciale : vue complète de la sculpture, du bassin et des circulations voisines.' },
        { alt: 'Deux vues fournies d’une installation réfléchissante en forme de baleine dans son environnement architectural', caption: 'Deux vues de référence d’un même agencement pour étudier les reflets, la distance de lecture et le bord de l’eau.' },
      ],
      specification: [['Direction de conception', 'Point focal sculptural réfléchissant ; forme originale développée pour le site.'], ['Matériau et finition', 'Orientation acier inoxydable ; nuance et finition miroir ou brossée validées sur échantillons.'], ['Dimensions', 'Selon le site. Fournissez un plan en pieds/pouces ou en unités métriques ; aucune taille standard n’est présumée.']],
      review: ['Parcours des clients, dégagements accessibles et emprise au sol.', 'Interfaces avec le bassin, accès de nettoyage et exposition aux éclaboussures.', 'Reflets et éblouissement sous l’éclairage réel du projet.'],
      faq: [['Cette direction convient-elle sans bassin ?', 'Oui, une installation dans un hall sec peut être étudiée. Le socle, la circulation, l’éclairage et l’entretien seront développés pour ce contexte.'], ['Comment le prix est-il établi ?', 'Une proposition suit l’étude du site, du dessin original, de l’échelle, de la finition, de la structure, de la destination et de la pose. Ces images de référence ne correspondent pas à un prix de produit fixe.']],
      relatedLabels: ['Guide de préparation d’une sculpture de hall', 'Finition miroir de l’inox', 'Service hôtels et resorts'],
    },
    'vertical-atrium-sculpture': {
      title: 'Sculpture verticale pour un atrium à plusieurs niveaux', category: 'Atrium / repère intérieur',
      intro: 'Une sculpture d’atrium se voit depuis plusieurs étages. Développez sa silhouette et son échelle avec l’équipe du bâtiment, en étudiant ensemble les dégagements, les interfaces structurelles et l’accès de pose.',
      disclosure: 'Références d’atriums commerciaux autorisées, et non projets hôteliers achevés par WEIERYANG. La forme, les fixations et les matériaux photographiés ne sont proposés ni comme spécifications vérifiées ni comme produit à reproduire.',
      images: [
        { alt: 'Installation verticale élancée dans un atrium commercial à plusieurs niveaux', caption: 'Référence d’atrium commercial : composition verticale complète face aux étages voisins.' },
        { alt: 'Partie basse d’une installation d’atrium et espace piéton adjacent', caption: 'Vue de référence pour étudier le pied et le dégagement piéton ; les fixations restent non vérifiées.' },
        { alt: 'Installation d’atrium vue à travers les niveaux et les garde-corps intérieurs', caption: 'Vue de référence des perspectives entre étages et du contexte architectural.' },
      ],
      specification: [['Direction de conception', 'Composition verticale originale coordonnée avec l’architecture de l’atrium.'], ['Matériau et finition', 'Choisis après examen de la forme, de la lumière, de l’entretien et des exigences structurelles.'], ['Dimensions', 'Définies selon les étages, la hauteur libre et les distances de vue ; pieds/pouces ou unités métriques acceptés.']],
      review: ['Vues depuis l’entrée, les étages et les principaux parcours des clients.', 'Points d’appui, étude structurelle locale et interfaces du bâtiment.', 'Parcours de levage, zones d’assemblage, protection et accès d’entretien futur.'],
      faq: [['Pouvez-vous étudier un atrium existant ?', 'Oui. Fournissez les plans, une coupe ou les hauteurs libres, des photos et la période de pose souhaitée. L’accès et la protection des zones occupées font partie de l’étude initiale.'], ['Une installation suspendue est-elle comprise ?', 'Le principe de support est développé pour chaque conception et bâtiment. Une photo ne démontre pas un système de suspension vérifié ; les responsabilités structurelles et les autorisations locales doivent être convenues dans la proposition.']],
      relatedLabels: ['Guide de préparation d’une sculpture d’atrium', 'Processus de sculpture sur mesure', 'Service hôtels et resorts'],
    },
    'tree-canopy-sculpture': {
      title: 'Sculptures en arbre et en canopée pour un paysage d’accueil', category: 'Arrivée / paysage',
      intro: 'Laissez le parcours d’arrivée guider la sculpture. Les références d’arbres et de canopées proposent différentes façons de créer un point focal, de cadrer un espace piéton et de relier une œuvre au paysage.',
      disclosure: 'Références paysagères autorisées montrant des œuvres différentes, et non plusieurs vues d’un produit. Une apparence dorée ne confirme ni nuance de métal ni revêtement. Elles ne sont pas présentées comme des commandes hôtelières WEIERYANG.',
      images: [
        { alt: 'Sculpture en arbre d’apparence dorée près d’un dallage et d’un bâtiment en construction', caption: 'Référence en arbre : vue complète de la silhouette ramifiée et de l’espace d’arrivée.' },
        { alt: 'Deux références paysagères distinctes en canopée, aux surfaces dorée et rouge', caption: 'Deux canopées différentes pour comparer le rythme spatial et l’orientation de finition.' },
      ],
      specification: [['Direction de conception', 'Formes originales d’arbre ou de canopée, développées avec le paysage et les vues d’approche.'], ['Matériau et finition', 'Métal et système de revêtement confirmés après étude de l’exposition et validation des échantillons.'], ['Dimensions', 'Emprise et hauteur propres au projet, coordonnées avec les parcours piétons et véhicules.']],
      review: ['Vues d’arrivée, dégagements piétons, interfaces avec le dallage et le paysage.', 'Exposition au vent, drainage, conditions de corrosion et entretien.', 'Responsabilités des fondations, ancrage, accès de livraison et assemblage.'],
      faq: [['La couleur et la silhouette peuvent-elles être adaptées à notre paysage ?', 'Oui. Une création originale et une finition peuvent être développées autour de l’architecture et des plantations. Les références guident la discussion sans promettre la copie d’une œuvre existante.'], ['Une sculpture en canopée peut-elle abriter ?', 'Un abri ou une ombre utilisable constitue une exigence distincte. Il faut l’étudier explicitement avec les charges, le drainage, la sécurité et les autorisations locales ; les références décoratives ne prouvent pas ces fonctions.']],
      relatedLabels: ['Cahier des charges d’une sculpture d’arrivée', 'Service de sculpture paysagère', 'Choix de l’inox pour l’extérieur'],
    },
    'bird-landmark-sculpture': {
      title: 'Sculpture monumentale d’oiseau en acier inoxydable', category: 'Site public / repère monumental',
      intro: 'Un repère monumental commence par une forme et un plan de livraison crédible. Notre suivi de chantier au Moyen-Orient offre une base concrète pour discuter d’un oiseau sur mesure, de l’assemblage segmenté et de la pose sur site.',
      disclosure: 'Photographies vérifiées d’une phase de chantier sur un site public au Moyen-Orient. Elles documentent l’assemblage et la pose, pas un hôtel achevé ni une commande américaine. Les nouveaux dessins et périmètres de livraison nécessitent une étude distincte.',
      images: [
        { alt: 'Sculpture monumentale d’oiseau en inox pendant sa pose sur un site public au Moyen-Orient', caption: 'Suivi de chantier vérifié au Moyen-Orient : pose sur site en cours.' },
        { alt: 'Assemblage structurel segmenté de l’oiseau monumental en inox pendant le chantier', caption: 'Document de chantier sur l’assemblage structurel segmenté ; ce n’est pas une photo de projet achevé.' },
        { alt: 'Alignement d’éléments d’aile répétés en inox lors de la pose du monument', caption: 'Document de chantier : alignement et pose des éléments d’aile répétés.' },
      ],
      specification: [['Direction de conception', 'Oiseau monumental original dont la géométrie et la structure sont développées pour le site.'], ['Matériau et finition', 'Acier inoxydable ; nuance, finition et exigences d’exposition confirmées pour le nouveau projet.'], ['Dimensions', 'Selon le site ; plans, zone du socle et accès de levage nécessaires avant de fixer le périmètre.']],
      review: ['Vues principales, échelle souhaitée et relation avec l’espace public.', 'Coordination structurelle, fondations et autorisations locales.', 'Segments d’expédition, plan de levage, accès au site et responsabilités de pose.'],
      faq: [['Que vérifient ces photographies ?', 'Elles vérifient la phase de chantier documentée sur un site public au Moyen-Orient, dont l’assemblage structurel et la pose. Elles n’attestent ni hôtel américain achevé, ni spécifications fixes, ni prix d’un nouveau projet.'], ['Quel accompagnement pouvez-vous fournir ?', 'WEIERYANG peut coordonner la conception sculpturale, le développement structurel, la fabrication, l’emballage export et les conseils de pose à l’étranger. Les travaux de site, l’ingénierie locale, le levage et les responsabilités des poseurs sont définis dans la proposition.']],
      relatedLabels: ['Suivi de chantier au Moyen-Orient', 'Éléments de preuve des projets', 'Facteurs de coût d’une grande sculpture extérieure'],
    },
  },
  zh: {
    'mirror-lobby-sculpture': {
      title: '大堂与水景镜面雕塑', category: '大堂 / 水景',
      intro: '反射焦点需要合适的空间。先评估宾客动线、水景边界和周边建筑，再为您的大堂发展独立的雕塑设计。',
      disclosure: '获授权的商业空间参考，不作为 WEIERYANG 已完成酒店作品展示。酒店用途是拟议应用；图片用于启发原创的场地定制设计。',
      images: [
        { alt: '玻璃商业室内的反光鲸形雕塑、悬挂球体与水池', caption: '商业空间参考：完整展示雕塑、水池与周边通行空间。' },
        { alt: '反光鲸形装置及其建筑环境的两张用户提供参考图', caption: '同一空间布置的两张参考视图，用于讨论反射、观看距离与水景边界。' },
      ],
      specification: [['设计方向', '反射型雕塑焦点；按场地发展原创形态。'], ['材料与饰面', '不锈钢方向；牌号及镜面或拉丝效果通过样板确认。'], ['尺寸', '按场地确定。请提供标明英尺/英寸或公制的平面图，不预设标准尺寸。']],
      review: ['宾客路线、无障碍净距与实际占地。', '水景接口、清洁检修通道与溅水暴露。', '项目实际灯光下的反射和眩光。'],
      faq: [['没有水景也能采用这一方向吗？', '可以评估干式大堂装置。底座、宾客动线、灯光和维护方案需结合该场地确定。'], ['价格如何确定？', '评估场地、原创设计、尺度、饰面、结构、目的地和安装范围后形成方案报价。参考图不对应固定产品售价。']],
      relatedLabels: ['酒店大堂规划指南', '镜面不锈钢饰面', '酒店与度假村服务'],
    },
    'vertical-atrium-sculpture': {
      title: '多层中庭竖向雕塑', category: '中庭 / 室内地标',
      intro: '中庭雕塑会被多个楼层同时观看。与建筑团队共同确定轮廓和尺度，将净距、结构接口及安装通道一并考虑。',
      disclosure: '获授权的商业中庭参考，不是 WEIERYANG 已完成酒店作品。照片中的形态、固定系统与材料不作为已核实规格，也不作为复制产品出售。',
      images: [
        { alt: '多层商业中庭内的细长竖向装置', caption: '商业中庭参考：竖向构图与周边楼层的完整关系。' },
        { alt: '中庭装置下部与相邻行人空间', caption: '用于讨论底部区域和通行净距的参考视图；固定细节尚未核实。' },
        { alt: '隔着楼层与室内栏杆观看中庭装置', caption: '跨楼层视线与建筑环境的参考视图。' },
      ],
      specification: [['设计方向', '与中庭建筑协调的原创竖向构图。'], ['材料与饰面', '评估形态、灯光、维护和结构要求后选择。'], ['尺寸', '根据楼层、净高与观看距离确定，接受英尺/英寸或公制。']],
      review: ['入口、上层楼面和主要宾客路线的视线。', '支撑位置、当地结构审核与建筑接口。', '吊装路线、组装区域、保护措施和后续维护通道。'],
      faq: [['能评估现有中庭吗？', '可以。请提供平面图、剖面图或净高、现场照片和目标安装窗口。通道及使用中区域的保护属于初次评估内容。'], ['是否包含悬挂安装？', '支撑方式需按设计和建筑确定。照片不能证明已核实的悬挂系统；结构责任与当地审批需在方案中确认。']],
      relatedLabels: ['中庭雕塑规划指南', '定制雕塑流程', '酒店与度假村服务'],
    },
    'tree-canopy-sculpture': {
      title: '入口景观树形与伞冠雕塑', category: '入口 / 景观',
      intro: '让到达动线决定雕塑。树形与伞冠参考以不同方式形成焦点、界定行人空间，并与周边景观建立联系。',
      disclosure: '获授权的景观参考，展示不同作品，并非同一产品的多个视角。金色外观不能确认金属牌号或涂层。图片不作为 WEIERYANG 酒店作品展示。',
      images: [
        { alt: '铺装与在建建筑旁的金色外观树形雕塑', caption: '树形参考：完整展示分枝轮廓及入口空间环境。' },
        { alt: '金色外观和红色表面的两件不同伞冠形景观参考', caption: '两件不同的伞冠参考，用于比较空间节奏与饰面方向。' },
      ],
      specification: [['设计方向', '结合景观和到达视线发展原创树形或伞冠形态。'], ['材料与饰面', '评估暴露条件并批准样板后，确认金属和涂层体系。'], ['尺寸', '按项目确定占地与高度，与行人及车辆路线协调。']],
      review: ['到达视线、行人净距、铺装与景观接口。', '风暴露、排水、腐蚀条件与日常维护。', '基础责任、锚固、运输通道与组装。'],
      faq: [['颜色和轮廓可以按我们的景观设计吗？', '可以围绕建筑与植物发展原创设计和饰面方向。参考图用于讨论，不构成复制现有作品的承诺。'], ['伞冠雕塑能遮雨或遮阳吗？', '遮雨或可用遮阴属于独立设计要求，必须结合荷载、排水、安全和当地审批明确评估；装饰参考图不能证明这些功能。']],
      relatedLabels: ['入口雕塑场地简报', '景观雕塑服务', '户外不锈钢选材'],
    },
    'bird-landmark-sculpture': {
      title: '飞鸟造型不锈钢地标雕塑', category: '公共场地 / 地标',
      intro: '地标需要形态，也需要可信的交付计划。我们的中东施工记录为讨论定制飞鸟雕塑、分段组装和现场安装协调提供实际起点。',
      disclosure: '来自中东公共场地、已核实的施工阶段照片，记录组装与安装工作，不代表已完成酒店或美国项目。新设计与交付范围需要单独评估。',
      images: [
        { alt: '中东公共场地正在安装的飞鸟造型不锈钢地标', caption: '已核实的中东施工记录：现场安装进行中。' },
        { alt: '不锈钢飞鸟地标施工中的分段结构组装', caption: '分段结构组装的施工阶段记录，不是竣工照片。' },
        { alt: '地标安装期间对齐重复不锈钢翼片构件', caption: '施工阶段记录：重复翼片构件的对齐与安装。' },
      ],
      specification: [['设计方向', '原创飞鸟地标，按场地发展几何形态与结构。'], ['材料与饰面', '不锈钢；按新项目确认牌号、饰面和暴露条件。'], ['尺寸', '按场地确定；锁定范围前需图纸、底座区域与吊装通道。']],
      review: ['主要视线、预期尺度与公共空间关系。', '结构设计协调、基础与当地审批。', '运输分段、吊装方案、现场通道及安装责任。'],
      faq: [['这些照片能核实什么？', '它们核实中东公共场地记录中的施工阶段，包括结构组装与安装；不能证明已完成美国酒店项目、固定产品规格或新项目价格。'], ['可以提供哪些交付支持？', 'WEIERYANG 可协调雕塑设计、结构深化、制作、出口包装和海外安装指导。场地施工、当地工程审核、吊装和安装方责任需在项目方案中界定。']],
      relatedLabels: ['中东施工记录', '项目证据', '大型户外雕塑成本因素'],
    },
  },
};

export function localizeSculpture(product, language = 'en') {
  if (!product || language === 'en') return product;
  const translated = translations[language]?.[product.slug];
  if (!translated) return product;
  const { images, relatedLabels, ...fields } = translated;
  return {
    ...product, ...fields,
    images: product.images.map((image, index) => ({ ...image, ...images[index] })),
    related: product.related.map(([, path], index) => [relatedLabels[index], path]),
  };
}
